---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-echo-server
  name: python-echo-server
  namespace: python-echo-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-echo-server
  template:
    metadata:
      labels:
        app: python-echo-server
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - python-echo-server
              topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: docker.io/library/python-echo-server:latest
        name: python-echo-server
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: python-echo-server-svc
  namespace: python-echo-server
  labels:
    app: python-echo-server
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: python-echo-server
